"""Deterministic contracts and evaluation components for Stoic Derived signals."""

from .alignment import (
    AlignmentFailure,
    AlignmentOutcome,
    CausalAligner,
    CausalSnapshot,
    FinalizedSeriesBatch,
)
from .compiler import (
    CompilationBlocker,
    CompilationReadiness,
    ProductionCompilation,
    StrategyProgram,
    compile_production_release,
    production_readiness,
)
from .engine import EngineCreation, SignalEngine
from .model import (
    CONFIDENCE_MAX,
    CONFIDENCE_MIN,
    FIXED_TIMEFRAME_PLANS,
    SCHEMA_VERSION,
    TIMEFRAME_PLANS,
    CoverageGap,
    Decision,
    Direction,
    EvaluationBatch,
    MarketLineage,
    RationalR,
    Role,
    SetupType,
    SignalBatch,
    SignalDecision,
    SignalRecord,
    SignalType,
    SignalValidationError,
    Suppression,
    SuppressionCode,
    TimeframePlan,
    canonical_json_bytes,
    timeframe_from_release_value,
    timeframe_from_rulebook,
)

__all__ = [
    "CONFIDENCE_MAX",
    "CONFIDENCE_MIN",
    "FIXED_TIMEFRAME_PLANS",
    "SCHEMA_VERSION",
    "TIMEFRAME_PLANS",
    "AlignmentFailure",
    "AlignmentOutcome",
    "CausalAligner",
    "CausalSnapshot",
    "CompilationBlocker",
    "CompilationReadiness",
    "CoverageGap",
    "Decision",
    "Direction",
    "EngineCreation",
    "EvaluationBatch",
    "FinalizedSeriesBatch",
    "MarketLineage",
    "ProductionCompilation",
    "RationalR",
    "Role",
    "SetupType",
    "SignalBatch",
    "SignalDecision",
    "SignalEngine",
    "SignalRecord",
    "SignalType",
    "SignalValidationError",
    "StrategyProgram",
    "Suppression",
    "SuppressionCode",
    "TimeframePlan",
    "canonical_json_bytes",
    "compile_production_release",
    "production_readiness",
    "timeframe_from_release_value",
    "timeframe_from_rulebook",
]
